### ISSUE TITLE
Looks unsafe the session checker or whatever looks like a logger

### ISSUE THREAD

**Issue by XxAwesqmexX** [KillerKillsKillers/XFlipperMod#1]
In the src/main/java/me/mindlessly/notenoughcoins/Reference.java
you see:
public static final Logger logger = LogManager.getLogger("TokenManager");
which looks like a session stealer idk if u can change it but it doesnt look safe lol

**Comment by KillerKillsKillers** [comment]
Fixed it also here I have a Anti Rat mod:
https://github.com/KillerKillsKillers/RatBeGone
